site_name: Django REST Framework Pipeline Views

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Serializer Inference: inference.md
  - Logic Blocks: logic_blocks.md
  - Conditional Logic Paths: conditionals.md
  - Async Logic Callables: async.md
  - OpenAPI Schema: schema.md
  - Metadata: metadata.md
  - Miscellaneous: misc.md

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - css/docs.css
