site_name: Pipeline Views

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Serializer Inference: inference.md
  - Logic Blocks: logic_blocks.md
  - Conditional Logic Paths: conditionals.md
  - Async Logic Callables: async.md
  - OpenAPI Schema: schema.md
  - Metadata: metadata.md
  - Miscellaneous: misc.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:  # https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md
    - python
    - console
    - json

markdown_extensions:
  pymdownx.highlight:
    anchor_linenums: true
  pymdownx.inlinehilite:
  pymdownx.snippets:
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search:
  - mermaid2:
      version: 9.4.3

extra_css:
  - css/docs.css
