site_name: Django REST Framework Pipeline Views
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Serializer Inference: serializer_inference.md
  - Logic Blocks: logic_blocks.md
  - Conditional Logic Paths: conditional_logic_paths.md
  - Miscellaneous: misc.md
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
    - yaml
